debug: true

# spring boot
spring:
  application.name: line-bot
  profiles.active: dev

# line config
# https://github.com/line/line-bot-sdk-java/tree/master/line-bot-spring-boot
line.bot:
  handler.enabled: true
  handler.path: /callback
  channel-token: KjfBts3aROBmubQAp8QQmNC38B12Lu5XIv9O19RDraQRRVYs64RRgF8f75oJlbVBG/qtwPsrdgtPm0yCF6+Ap/GWpqHUGRQspjDxhnwcCVQN5tP6SpwrLdzcC6uB22fdgaTjHB/vi584qy8Tho8xKQdB04t89/1O/w1cDnyilFU=
  channel-secret: a431b9c10fec7f1ec866278ad26a7d86
  channelTokenSupplyMode: fixed
  connectTimeout: 60000
  readTimeout: 60000
  writeTimeout: 60000
